//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 Tim Seagren.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborOidcSpec) DeepCopyInto(out *HarborOidcSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborOidcSpec.
func (in *HarborOidcSpec) DeepCopy() *HarborOidcSpec {
	if in == nil {
		return nil
	}
	out := new(HarborOidcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborProjectsMetadataSpec) DeepCopyInto(out *HarborProjectsMetadataSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborProjectsMetadataSpec.
func (in *HarborProjectsMetadataSpec) DeepCopy() *HarborProjectsMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(HarborProjectsMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborProjectsSpec) DeepCopyInto(out *HarborProjectsSpec) {
	*out = *in
	out.MetaData = in.MetaData
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborProjectsSpec.
func (in *HarborProjectsSpec) DeepCopy() *HarborProjectsSpec {
	if in == nil {
		return nil
	}
	out := new(HarborProjectsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborProvisioner) DeepCopyInto(out *HarborProvisioner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborProvisioner.
func (in *HarborProvisioner) DeepCopy() *HarborProvisioner {
	if in == nil {
		return nil
	}
	out := new(HarborProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarborProvisioner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborProvisionerAwsSpec) DeepCopyInto(out *HarborProvisionerAwsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborProvisionerAwsSpec.
func (in *HarborProvisionerAwsSpec) DeepCopy() *HarborProvisionerAwsSpec {
	if in == nil {
		return nil
	}
	out := new(HarborProvisionerAwsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborProvisionerHarborSpec) DeepCopyInto(out *HarborProvisionerHarborSpec) {
	*out = *in
	if in.HarborProjects != nil {
		in, out := &in.HarborProjects, &out.HarborProjects
		*out = make([]HarborProjectsSpec, len(*in))
		copy(*out, *in)
	}
	if in.Robots != nil {
		in, out := &in.Robots, &out.Robots
		*out = make([]HarborRobotSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RetentionPolicies != nil {
		in, out := &in.RetentionPolicies, &out.RetentionPolicies
		*out = make([]HarborRetentionPoliciesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Oidc != nil {
		in, out := &in.Oidc, &out.Oidc
		*out = make([]HarborOidcSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborProvisionerHarborSpec.
func (in *HarborProvisionerHarborSpec) DeepCopy() *HarborProvisionerHarborSpec {
	if in == nil {
		return nil
	}
	out := new(HarborProvisionerHarborSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborProvisionerList) DeepCopyInto(out *HarborProvisionerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HarborProvisioner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborProvisionerList.
func (in *HarborProvisionerList) DeepCopy() *HarborProvisionerList {
	if in == nil {
		return nil
	}
	out := new(HarborProvisionerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarborProvisionerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborProvisionerSpec) DeepCopyInto(out *HarborProvisionerSpec) {
	*out = *in
	out.Aws = in.Aws
	in.Harbor.DeepCopyInto(&out.Harbor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborProvisionerSpec.
func (in *HarborProvisionerSpec) DeepCopy() *HarborProvisionerSpec {
	if in == nil {
		return nil
	}
	out := new(HarborProvisionerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborProvisionerStatus) DeepCopyInto(out *HarborProvisionerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborProvisionerStatus.
func (in *HarborProvisionerStatus) DeepCopy() *HarborProvisionerStatus {
	if in == nil {
		return nil
	}
	out := new(HarborProvisionerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRetentionPoliciesRulesScopeSelectors) DeepCopyInto(out *HarborRetentionPoliciesRulesScopeSelectors) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = make([]HarborRetentionPoliciesRulesScopeSelectorsRepository, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRetentionPoliciesRulesScopeSelectors.
func (in *HarborRetentionPoliciesRulesScopeSelectors) DeepCopy() *HarborRetentionPoliciesRulesScopeSelectors {
	if in == nil {
		return nil
	}
	out := new(HarborRetentionPoliciesRulesScopeSelectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRetentionPoliciesRulesScopeSelectorsRepository) DeepCopyInto(out *HarborRetentionPoliciesRulesScopeSelectorsRepository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRetentionPoliciesRulesScopeSelectorsRepository.
func (in *HarborRetentionPoliciesRulesScopeSelectorsRepository) DeepCopy() *HarborRetentionPoliciesRulesScopeSelectorsRepository {
	if in == nil {
		return nil
	}
	out := new(HarborRetentionPoliciesRulesScopeSelectorsRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRetentionPoliciesRulesSpec) DeepCopyInto(out *HarborRetentionPoliciesRulesSpec) {
	*out = *in
	in.ScopeSelectors.DeepCopyInto(&out.ScopeSelectors)
	out.TagSelectors = in.TagSelectors
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRetentionPoliciesRulesSpec.
func (in *HarborRetentionPoliciesRulesSpec) DeepCopy() *HarborRetentionPoliciesRulesSpec {
	if in == nil {
		return nil
	}
	out := new(HarborRetentionPoliciesRulesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRetentionPoliciesRulesTagSelectors) DeepCopyInto(out *HarborRetentionPoliciesRulesTagSelectors) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRetentionPoliciesRulesTagSelectors.
func (in *HarborRetentionPoliciesRulesTagSelectors) DeepCopy() *HarborRetentionPoliciesRulesTagSelectors {
	if in == nil {
		return nil
	}
	out := new(HarborRetentionPoliciesRulesTagSelectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRetentionPoliciesScopeSpec) DeepCopyInto(out *HarborRetentionPoliciesScopeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRetentionPoliciesScopeSpec.
func (in *HarborRetentionPoliciesScopeSpec) DeepCopy() *HarborRetentionPoliciesScopeSpec {
	if in == nil {
		return nil
	}
	out := new(HarborRetentionPoliciesScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRetentionPoliciesScopeTriggerSettingsSpec) DeepCopyInto(out *HarborRetentionPoliciesScopeTriggerSettingsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRetentionPoliciesScopeTriggerSettingsSpec.
func (in *HarborRetentionPoliciesScopeTriggerSettingsSpec) DeepCopy() *HarborRetentionPoliciesScopeTriggerSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(HarborRetentionPoliciesScopeTriggerSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRetentionPoliciesScopeTriggerSpec) DeepCopyInto(out *HarborRetentionPoliciesScopeTriggerSpec) {
	*out = *in
	out.Settings = in.Settings
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRetentionPoliciesScopeTriggerSpec.
func (in *HarborRetentionPoliciesScopeTriggerSpec) DeepCopy() *HarborRetentionPoliciesScopeTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(HarborRetentionPoliciesScopeTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRetentionPoliciesSpec) DeepCopyInto(out *HarborRetentionPoliciesSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]HarborRetentionPoliciesRulesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Scope = in.Scope
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRetentionPoliciesSpec.
func (in *HarborRetentionPoliciesSpec) DeepCopy() *HarborRetentionPoliciesSpec {
	if in == nil {
		return nil
	}
	out := new(HarborRetentionPoliciesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRobotPermissionsAccessSpec) DeepCopyInto(out *HarborRobotPermissionsAccessSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRobotPermissionsAccessSpec.
func (in *HarborRobotPermissionsAccessSpec) DeepCopy() *HarborRobotPermissionsAccessSpec {
	if in == nil {
		return nil
	}
	out := new(HarborRobotPermissionsAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRobotPermissionsSpec) DeepCopyInto(out *HarborRobotPermissionsSpec) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]HarborRobotPermissionsAccessSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRobotPermissionsSpec.
func (in *HarborRobotPermissionsSpec) DeepCopy() *HarborRobotPermissionsSpec {
	if in == nil {
		return nil
	}
	out := new(HarborRobotPermissionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborRobotSpec) DeepCopyInto(out *HarborRobotSpec) {
	*out = *in
	if in.permission != nil {
		in, out := &in.permission, &out.permission
		*out = make([]HarborRobotPermissionsSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborRobotSpec.
func (in *HarborRobotSpec) DeepCopy() *HarborRobotSpec {
	if in == nil {
		return nil
	}
	out := new(HarborRobotSpec)
	in.DeepCopyInto(out)
	return out
}
