# permissions for end users to edit harbors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harbor-editor-role
rules:
- apiGroups:
  - test.tim.local
  resources:
  - harbors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.tim.local
  resources:
  - harbors/status
  verbs:
  - get
