
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - test.tim.local
  resources:
  - harborprovisioners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.tim.local
  resources:
  - harborprovisioners/finalizers
  verbs:
  - update
- apiGroups:
  - test.tim.local
  resources:
  - harborprovisioners/status
  verbs:
  - get
  - patch
  - update
